version: '3.8'
services:
    # mysql database
    mysql-database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel-network

    # redis database
    redis-database:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data
        networks:
            - laravel-network

    # phpmyadmin server
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8010:80
        restart: unless-stopped
        depends_on:
            - mysql-database
        environment:
            - PMA_ARBITRARY=1
        networks:
            - laravel-network

    # laravel app
    laravel-app:
        build:
            args:
                user: zaman
                uid: 1000
            context: ./.docker
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - APP_ENV=${APP_ENV}
            - DB_HOST=mysql-database
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        volumes:
            - ./:/var/www/html:cached
            - ./.docker/php-fpm.ini:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - mysql-database
            - redis-database
        networks:
            - laravel-network

    # Composer
    composer:
        image: composer:latest
        volumes:
            - ./:/var/www/html:cached
        working_dir: /var/www/html
        command: composer install
        depends_on:
            - laravel-app
        networks:
            - laravel-network

    # Nginx server
    nginx-server:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html:cached
            - ./.docker/nginx:/etc/nginx/conf.d
            - ./.docker/nginx/ssl:/etc/nginx/conf.d/ssl
        depends_on:
            - laravel-app
        networks:
            - laravel-network

# Networks
networks:
    laravel-network:
        driver: bridge
# Volumes
volumes:
    mysql-data: ~
    redis-data: ~
