version: '3.8'
services:
    nginx:
        image: nginx:alpine
        container_name: latavel-container
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www/html:cached
            - ./docker/nginx:/etc/nginx/conf.d
            - ./docker/nginx/ssl:/etc/nginx/conf.d/ssl
        depends_on:
            - app
        networks:
            - laravel-network

    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: latavel-container-app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html:cached
            - ./docker/php/php-fpm.ini:/usr/local/etc/php/conf.d/custom.ini
            - ~/.ssh:/root/.ssh
        depends_on:
            - database
            - redis
        networks:
            - laravel-network

    database:
        image: mysql
        container_name: latavel-container-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        networks:
            - laravel-network

    redis:
        image: redis:alpine
        container_name: latavel-container-redis
        restart: unless-stopped
        ports:
            - 6379:6379
        volumes:
            - ./docker/redis:/data
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    laravel-volume:
        driver: local
