name: 🚀 Deploy Private Server Master
on:
  push:
    branches: [ test ]

jobs:
  deploy:
    name: 🎉 Laravel Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files to server
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: 207.180.201.234
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
