on:
  push:
    branches: [ master ]

name: 🚀 Deploy Private Server Master
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: 207.180.201.234
        username: ${{ secrets.ftp_zamanz_username }}
        password: ${{ secrets.ftp_zamanz_userpassword }}
        server-dir: /api.kzaman.me/
